//Test::LongQuestion
export const LQ_FETCH_QUESTION = "LQ_FETCH_QUESTION";
export const LQ_UPDATE_RESULT = "LQ_UPDATE_RESULT";
export const LQ_POST_RESULT = "LQ_POST_RESULT";
export const LQ_FILL_OUT_AFFINITIES = "LQ_FILL_OUT_AFFINITIES";
export const LQ_UPDATE_OPTION_SELECTED_ORDER =
  "LQ_UPDATE_OPTION_SELECTED_ORDER";

//Test::ShortQuestion
export const SQ_FETCH_SET = "SQ_FETCH_SET";
export const SQ_UPDATE_CURRENT_PAIR = "SQ_UPDATE_CURRENT_PAIR";
export const SQ_UPDATE_PAIR_SELECTED_CARD = "SQ_UPDATE_PAIR_SELECTED_CARD";
export const SQ_TOGGLE_CURRENT_PAIR = "SQ_TOGGLE_CURRENT_PAIR";
export const SQ_NEXT_PAIR = "SQ_NEXT_PAIR";
export const SQ_SET_ACTIVE_PAIR_ID = "SQ_SET_ACTIVE_PAIR_ID";

//Test::Status
export const STATUS_TOGGLE_LOADING = "STATUS_TOGGLE_LOADING";
export const STATUS_TOGGLE_TEST = "STATUS_TOGGLE_TEST";
export const STATUS_TOGGLE_SHORTQUESTION = "STATUS_TOGGLE_SHORTQUESTION";
export const STATUS_TOGGLE_LONGQUESTION = "STATUS_TOGGLE_LONGQUESTION";
export const STATUS_TOGGLE_RESULT = "STATUS_TOGGLE_RESULT";
