//LongQuestion
export const LQ_FETCH_QUESTION = "LQ::FETCH_QUESTION";
export const LQ_UPDATE_RESULT = "LQ::UPDATE_RESULT";
export const LQ_POST_RESULT = "LQ::POST_RESULT";
export const LQ_DELETE_QUESTION = "LQ::DELETE_QUESTION";
export const LQ_UPDATE_CHECK_OPTION_AND_RESULT =
  "LQ::UPDATE_CHECK_OPTION_AND_RESULT";

//ShortQuestion
export const SQ_FETCH_SET = "SQ::FETCH_SET";
export const SQ_UPDATE_CURRENT_PAIR = "SQ::UPDATE_CURRENT_PAIR";
export const SQ_UPDATE_PAIR_SELECTED_CARD = "SQ::UPDATE_PAIR_SELECTED_CARD";
export const SQ_TOGGLE_CURRENT_PAIR = "SQ::TOGGLE_CURRENT_PAIR";
export const SQ_NEXT_PAIR = "SQ::NEXT_PAIR";
