export const FETCH_QUESTION = "FETCH_QUESTION";
export const UPDATE_RESULT = "UPDATE_RESULT";
export const POST_RESULT = "POST_RESULT";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_CHECK_OPTION_AND_RESULT = "UPDATE_CHECK_OPTION_AND_RESULT";
